# Generated by Django 4.1.1 on 2022-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan", old_name="exculsive", new_name="exclusive",
        ),
        migrations.AlterField(
            model_name="service", name="icon", field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="service", name="name", field=models.CharField(max_length=300),
        ),
    ]
